### ISSUE TITLE
FEATURE: Check that paths exist during compilation

### ISSUE THREAD

**Issue by KaiserKarel** [magiclen/lazy-static-include#2]
In `debug` mode, the macro does not check that the actual path exists. Especially when converting from `include_{bytes | str}!`, which uses different paths, it would be nice to have this checked.

**Comment by magiclen** [comment]
I am planning to create a crate which provides a procedural macro to check for path existence during compile time.

**Comment by magiclen** [comment]
The new crate [`manifest-dir-macros`](https://crates.io/crates/manifest-dir-macros) has been done. And with it, now the `lazy-static-include` crate can check the existence of paths in debug mode during compile time.
